# Generated by Django 4.0.4 on 2022-10-31 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
