# Generated by Django 4.0.4 on 2022-10-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_publicaion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.CharField(max_length=30)),
                ('contenido', models.CharField(blank=True, max_length=3000, null=True)),
                ('firma', models.TextField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
