# Generated by Django 4.0.4 on 2022-11-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='image_dos',
            field=models.ImageField(blank=True, null=True, upload_to='paraclinica'),
        ),
        migrations.AddField(
            model_name='registro',
            name='image_tres',
            field=models.ImageField(blank=True, null=True, upload_to='paraclinica'),
        ),
    ]
