# Generated by Django 4.0.4 on 2022-10-31 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0002_alter_registro_contenido_alter_registro_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_de_publicaion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 19, 55, 45, 544460)),
        ),
        migrations.AlterField(
            model_name='registro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
