# Generated by Django 4.0.4 on 2022-10-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0003_alter_registro_fecha_de_publicaion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_de_publicaion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
