# Generated by Django 4.0.4 on 2022-11-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0004_registro_usuario_alter_registro_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='firma',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
