# Generated by Django 4.0.4 on 2022-10-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0004_alter_registro_fecha_de_publicaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='fecha_de_publicaion',
            new_name='fecha',
        ),
    ]
