# Generated by Django 4.0.4 on 2022-11-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_remove_configuracion_nombre_usuario_and_more'),
        ('historiaclinica', '0005_rename_fecha_de_publicaion_registro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.paciente'),
            preserve_default=False,
        ),
    ]
