# Generated by Django 4.0.4 on 2022-11-07 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historiaclinica', '0005_alter_registro_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='registro',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registros', to=settings.AUTH_USER_MODEL),
        ),
    ]
