# Generated by Django 4.0.4 on 2022-11-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_remove_configuracion_nombre_usuario_and_more'),
        ('historiaclinica', '0006_registro_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panel.paciente'),
        ),
    ]
