# Generated by Django 4.0.4 on 2022-11-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0006_remove_registro_usuario_alter_registro_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='firma',
        ),
    ]
