# Generated by Django 4.0.4 on 2022-11-04 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historiaclinica', '0008_alter_registro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='firmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
