# Generated by Django 4.0.4 on 2022-11-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_remove_configuracion_nombre'),
        ('historiaclinica', '0009_alter_registro_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='firma',
        ),
        migrations.AlterField(
            model_name='registro',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panel.paciente'),
        ),
    ]
