# Generated by Django 4.0.4 on 2022-11-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_remove_configuracion_nombre'),
        ('historiaclinica', '0010_remove_registro_firma_alter_registro_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panel.paciente'),
        ),
    ]
