# Generated by Django 4.0.4 on 2022-11-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0014_alter_registro_firma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='firma',
            new_name='user',
        ),
    ]
