# Generated by Django 4.0.4 on 2022-11-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tab', models.CharField(max_length=30)),
                ('nombre_clinica', models.CharField(default='Nombre Clinica', max_length=20)),
                ('nombre', models.CharField(default='Nombre', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
    ]
