# Generated by Django 4.0.4 on 2022-11-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_CI', models.IntegerField()),
                ('numero_contacto', models.IntegerField()),
                ('motivo_consulta', models.TextField(max_length=100)),
                ('fecha_solicitada', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ConfiguracionWeb',
        ),
    ]
