# Generated by Django 4.0.4 on 2022-11-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpaciente',
            name='disponibilidad_horaria',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
