# Generated by Django 4.0.4 on 2022-11-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_solicitudpaciente_delete_configuracionweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpaciente',
            name='fecha_solicitada',
        ),
    ]
