# Generated by Django 4.0.4 on 2022-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_solicitudpaciente_disponibilidad_horaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpaciente',
            old_name='disponibilidad_horaria',
            new_name='disponibilidad_horaria_final',
        ),
        migrations.AddField(
            model_name='solicitudpaciente',
            name='disponibilidad_horaria_inicial',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
