# Generated by Django 4.0.4 on 2022-11-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_solicitudpaciente_fecha_solicitada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpaciente',
            old_name='nombre_y_apellido',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='solicitudpaciente',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
