# Generated by Django 4.0.4 on 2022-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tab', models.CharField(max_length=30)),
                ('nombre_clinica', models.CharField(default='Nombre Clinica', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('fecha_de_nacimiento', models.DateField()),
                ('numero_CI', models.IntegerField(blank=True, null=True)),
                ('numero_contacto', models.IntegerField(blank=True, null=True)),
                ('motivo_consulta', models.CharField(max_length=20)),
            ],
        ),
    ]
