# Generated by Django 4.0.4 on 2022-10-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('fecha_de_nacimiento', models.DateField()),
                ('numero_ci', models.IntegerField()),
                ('numero_contacto', models.IntegerField()),
                ('motivo_consulta', models.CharField(max_length=20)),
            ],
        ),
    ]
