# Generated by Django 4.0.4 on 2022-10-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nombre_clinica',
            field=models.CharField(default='Nombre Clinica', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_usuario',
            field=models.CharField(default='Nombre Usuario', max_length=20),
        ),
    ]
