# Generated by Django 4.0.4 on 2022-11-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_paciente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
