# Generated by Django 4.0.4 on 2022-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_rename_numero_ci_paciente_numero_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='index'),
        ),
    ]
