# Generated by Django 4.0.4 on 2022-11-10 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0004_alter_paciente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.CharField(max_length=30)),
                ('contenido', models.TextField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='paraclinica')),
                ('image_dos', models.ImageField(blank=True, null=True, upload_to='paraclinica')),
                ('image_tres', models.ImageField(blank=True, null=True, upload_to='paraclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panel.paciente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
