# Generated by Django 4.0.4 on 2022-11-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='slogan',
            field=models.CharField(default='slogan', max_length=50),
        ),
    ]
