# Generated by Django 4.0.4 on 2022-10-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_paciente_numero_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
