# Generated by Django 4.0.4 on 2022-11-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_configuracion_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=20),
        ),
    ]
