# Generated by Django 4.0.4 on 2022-11-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_remove_configuracion_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
