# Generated by Django 4.0.4 on 2022-11-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_configuracion_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre',
        ),
    ]
